// default package
// Generated 10-nov-2016 13:42:43 by Hibernate Tools 4.0.0.Final
package com.grupoB.proyecto.modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;
/**
 * Editorial generated by hbm2java
 */
@Entity
@Table(name = "editorial", catalog = "tiendaonlinefinal3")
public class Editorial implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	@Size(max=15)
	@NotNull
	private Integer idEditorial;
	@Size(max=15)
	@NotNull
	private Libro libro;
	@Size(max=45)
	@NotNull
	private String nombre;

	public Editorial() {
	}

	public Editorial(Libro libro, String nombre) {
		this.libro = libro;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEditorial", unique = true, nullable = false)
	public Integer getIdEditorial() {
		return this.idEditorial;
	}

	public void setIdEditorial(Integer idEditorial) {
		this.idEditorial = idEditorial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLibro", nullable = false)
	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/*
	@Override
	public String toString() {
		return "Editorial [idEditorial=" + idEditorial + ", libro=" + libro + ", nombre=" + nombre + "]";
	}*/

}
